/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wRnHKwPd1fn
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import axios from "axios";

/**
 * 
 * @param url 
 * @returns 
 */

function get(e:any) {
  e.preventDefault();

  console.log("first")
  axios.get("https://localhost:44369/api/Users?page=1&pageSize=10").then(function (response) {
    console.log(response);
  }).catch((e)=>{
    console.log(e);
  })
}

export function DispatchForm() {
  return (
    <div className="mx-auto max-w-md space-y-6">
      <div className="space-y-2">
        <h2 className="text-2xl font-bold">Vehicle Tracking</h2>
        <p className="text-gray-500 dark:text-gray-400">
          Enter the details for the vehicle tracking.
        </p>
      </div>
      <form className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="vehicle-token">Vehicle Token</Label>
          <div>
            <div className="mt-1 max-h-60 overflow-auto rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm">
              <div>Token 1</div>
              <div>Token 2</div>
              <div>Token 3</div>
            </div>
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="driver-id">Driver ID</Label>
          <Select id="driver-id">
            <SelectTrigger>
              <SelectValue placeholder="Select driver" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="driver-1">driver-1</SelectItem>
              <SelectItem value="driver-2">driver-2</SelectItem>
              <SelectItem value="driver-3">driver-3</SelectItem>
             
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="road-id">Road ID</Label>
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="Select road" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="road-1">Road 1</SelectItem>
              <SelectItem value="road-2">Road 2</SelectItem>
              <SelectItem value="road-3">Road 3</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="odometer">Odometer</Label>
          <Input
            id="odometer"
            placeholder="Enter odometer reading"
            type="number"
          />
        </div>
        <Button className="w-full" type="submit" onClick={get}>
          Submit
        </Button>
      </form>
    </div>
  );
}
