// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using FUEL_DISPATCH_API.Utils.Constants;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class BranchOffices
{
    [JsonIgnore] public virtual ICollection<BranchIsland>? BranchIslands { get; set; } = new List<BranchIsland>();
    [Required] public string? Code { get; set; }
    [JsonIgnore] public virtual Companies? Company { get; set; }

    [Required] public int CompanyId { get; set; }

    public DateTime? CreatedAt { get; set; } = DateTime.Now;

    public string? CreatedBy { get; set; }

    [Required] public string? Email { get; set; }
    public string? Email2 { get; set; }

    [Required] public string FullLocation { get; set; }

    public int Id { get; set; }
    [Required] public string Name { get; set; }

    [Phone, Required] public string Phone { get; set; }

    [Phone] public string? Phone2 { get; set; }

    [Required] public string Representative { get; set; }
    public string Status { get; set; } = ValidationConstants.ActiveStatus;
    public DateTime? UpdatedAt { get; set; } = DateTime.Now;
    public string? UpdatedBy { get; set; }
    [JsonIgnore] public virtual ICollection<UsersBranchOffices> UsersBranchOffices { get; set; } = new List<UsersBranchOffices>();
    [JsonIgnore] public virtual ICollection<Dispenser> Dispensers { get; set; } = new List<Dispenser>();
    [JsonIgnore] public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
    [JsonIgnore] public virtual ICollection<WareHouseMovement> WareHouseMovements { get; set; } = new List<WareHouseMovement>();
    [JsonIgnore] public virtual ICollection<WareHouse> WareHouses { get; set; } = new List<WareHouse>();
    [JsonIgnore] public virtual ICollection<Driver> Drivers { get; set; } = new List<Driver>();
    [JsonIgnore] public virtual ICollection<User> Users { get; set; } = new List<User>();

}