// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class BranchOffices
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? LocationId { get; set; }

    public string FullLocation { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Dispatch> Dispatch { get; set; } = new List<Dispatch>();

    public virtual Locations Location { get; set; }

    public virtual ICollection<Users> User { get; set; } = new List<Users>();
}