// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class CalculatedComsuption
{
    public int Id { get; set; }

    public int? VehicleId { get; set; }

    public decimal? Odometer { get; set; }

    public decimal Gallons { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? VehicleMeasure { get; set; }

    public decimal CalculatedComsuption1 { get; set; }

    public decimal? TotalCalculatedComsuption { get; set; }
}