// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class CompanyUser
{
    public int UserId { get; set; }

    public int CompanyId { get; set; }

    public virtual Companies Company { get; set; } = null!;

    public virtual User User { get; set; } = null!;
}