// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Companies
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? FullAddress { get; set; }

    public string? PostalCode { get; set; }

    public string? PhoneNumber { get; set; }

    public string? CompanyRNC { get; set; }

    public string? EmailAddress { get; set; }

    public string? Website { get; set; }

    public string? Industry { get; set; }

    public DateOnly? DateEstablished { get; set; }

    public string? CEOFounder { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public string? CreatedBy { get; set; }

    public string? UpdatedBy { get; set; }

    public virtual ICollection<User>? Users { get; set; }
    public virtual ICollection<CompanyUser> CompanyUser { get; set; } = new List<CompanyUser>();
}