// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class ComsuptionByMonth
{
    public int? Month { get; set; }

    public decimal? TotalFuelConsumed { get; set; }
}