// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Dispatch
{
    public int Id { get; set; }

    public int? DriverId { get; set; }

    public int? RoadId { get; set; }

    public int? RequestId { get; set; }

    public int? DispenserId { get; set; }

    public decimal? Odometer { get; set; }
    public int StoreId { get; set; }
    public string? Notes { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public decimal Gallons { get; set; }

    public int? BranchOfficeId { get; set; }

    public bool? IsForVehicle { get; set; }

    public int? VehicleId { get; set; }
    [JsonIgnore]
    public virtual BranchOffices? BranchOffice { get; set; }
    [JsonIgnore]
    public virtual Dispenser? Dispenser { get; set; }
    [JsonIgnore]
    public virtual Driver? Driver { get; set; }
    [JsonIgnore]
    public virtual Road? Road { get; set; }
    [JsonIgnore]
    public virtual Vehicle? Vehicle { get; set; } 
    public virtual Store? Store { get; set; }
}