// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Dispensers
{
    public int Id { get; set; }

    public string DispenserName { get; set; }

    public string FuelType { get; set; }

    public decimal MaxCapacity { get; set; }

    public decimal CurrentCapacity { get; set; }

    public string Location { get; set; }

    public DateTime? LastRefillDate { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Dispatch> Dispatch { get; set; } = new List<Dispatch>();
}