// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Dispatch
{
    public int Id { get; set; }

    public string VehicleToken { get; set; }

    public int DriverId { get; set; }

    public int RoadId { get; set; }

    public int? RequestId { get; set; }

    public int DispenserId { get; set; }

    public decimal Odometer { get; set; }

    public string Notes { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public decimal Gallons { get; set; }

    public int? BranchOfficeId { get; set; }

    public virtual BranchOffices BranchOffice { get; set; }

    public virtual Dispensers Dispenser { get; set; }

    public virtual Drivers Driver { get; set; }

    public virtual Roads Road { get; set; }

    public virtual Vehicles VehicleTokenNavigation { get; set; }
}