// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Drivers_MethodsOfProvideFuel
{
    public int DriverId { get; set; }

    public int MethodOfProvideFuelId { get; set; }

    public virtual Driver Driver { get; set; } = null!;

    public virtual MethodOfProvidingFuel MethodOfProvideFuel { get; set; } = null!;
}