// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Drivers
{
    public int Id { get; set; }
    [EmailAddress]
    public string Email { get; set; }

    public string FullName { get; set; }
    [Phone]
    public string PhoneNumber { get; set; }

    public DateTime BirthDate { get; set; }

    public string FullDirection { get; set; }

    public DateTime LicenceExpDate { get; set; }

    public string Status { get; set; }

    public decimal? MethodOfProvidingFuelAmount { get; set; }

    public string CreatedBy { get; set; }
    public DateTime? CreatedAt { get; set; }
    [MinLength(11), MaxLength(11)]
    public string Identification { get; set; }
    public string UpdatedBy { get; set; }
    public int? UserId { get; set; } 
    public  int VehicleId { get; set; } 
    public DateTime? UpdatedAt { get; set; }
    [JsonIgnore]
    public virtual ICollection<Dispatch> Dispatch { get; set; } = new List<Dispatch>();
    [JsonIgnore]
    public virtual ICollection<Users> User { get; set; } = new List<Users>();   
    public virtual Vehicles Vehicle {  get; set; }
    [JsonIgnore]
    public virtual ICollection<Vehicles> Vehicles { get; set; } = new List<Vehicles>();
    [JsonIgnore]
    public virtual ICollection<MethodsOfProvidingFuel> MethodOfProvideFuel { get; set; } = new List<MethodsOfProvidingFuel>();
}