// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Text.Json.Serialization;
using FUEL_DISPATCH_API.Utils.Constants;
#nullable enable
namespace FUEL_DISPATCH_API.DataAccess.Models;
public partial class Driver
{
    public int Id { get; set; }

    public string? Email { get; set; }

    public string? FullName { get; set; }

    public string? PhoneNumber { get; set; }

    public DateTime BirthDate { get; set; }

    public string? FullDirection { get; set; }

    public DateTime? LicenceExpDate { get; set; }

    public string? Status { get; set; } = ValidationConstants.ActiveStatus;
    public string? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; } = DateTime.Now;

    public string? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; } = DateTime.Now;

    public string? Identification { get; set; }

    public int? VehicleId { get; set; }
    [JsonIgnore]
    public virtual ICollection<WareHouseMovement>? WareHouseMovements { get; set; } = new List<WareHouseMovement>();
    [JsonIgnore]
    public virtual ICollection<User>? User { get; set; } = new List<User>();
    [JsonIgnore]
    public virtual Vehicle? Vehicle { get; set; }
    [JsonIgnore]
    public virtual ICollection<Vehicle>? VehicleNavigation { get; set; } = new List<Vehicle>();
    [JsonIgnore]
    public virtual ICollection<Request>? Requests { get; set; } = new List<Request>();
    [JsonIgnore]
    public virtual ICollection<EmployeeConsumptionLimits>? EmployeeConsumptionLimits { get; set; } = new List<EmployeeConsumptionLimits>();
    [JsonIgnore]
    public virtual ICollection<Booking>? Bookings { get; set; } = new List<Booking>();

}