// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Text.Json.Serialization;
using System;
using System.Collections.Generic;
using FUEL_DISPATCH_API.Utils.Constants;

namespace FUEL_DISPATCH_API.DataAccess.Models;
#nullable enable
public partial class Driver
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string FullName { get; set; } = null!;

    public string PhoneNumber { get; set; } = null!;

    public DateTime BirthDate { get; set; }

    public string FullDirection { get; set; } = null!;

    public DateTime LicenceExpDate { get; set; }

    public string Status { get; set; } = ValidationConstants.ActiveStatus;

    public decimal? MethodOfProvidingFuelAmount { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string? Identification { get; set; }

    public int? VehicleId { get; set; }
    [JsonIgnore]
    public virtual ICollection<WareHouseMovement> WareHouseMovements { get; set; } = new List<WareHouseMovement>();
    [JsonIgnore]
    public virtual ICollection<Drivers_MethodsOfProvideFuel> Drivers_MethodsOfProvideFuel { get; set; } = new List<Drivers_MethodsOfProvideFuel>();
    [JsonIgnore]
    public virtual ICollection<User> User { get; set; } = new List<User>();
    [JsonIgnore]
    public virtual Vehicle? Vehicle { get; set; }
    [JsonIgnore]
    public virtual ICollection<Vehicle> VehicleNavigation { get; set; } = new List<Vehicle>();
    [JsonIgnore]
    public virtual ICollection<Request> Requests { get; set; } = new List<Request>();

}