// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Drivers
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string FullName { get; set; }

    public string PhoneNumber { get; set; }

    public DateTime BirthDate { get; set; }

    public string FullDirection { get; set; }

    public DateTime LicenceExpDate { get; set; }

    public string Status { get; set; }

    public decimal? MethodOfProvidingFuelAmount { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Dispatch> Dispatch { get; set; } = new List<Dispatch>();

    public virtual ICollection<Users> Users { get; set; } = new List<Users>();

    public virtual ICollection<Vehicles> Vehicles { get; set; } = new List<Vehicles>();

    public virtual ICollection<MethodsOfProvidingFuel> MethodOfProvideFuel { get; set; } = new List<MethodsOfProvidingFuel>();
}