// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class FuelType
{
    public int Id { get; set; }

    public string? Type { get; set; }

    public virtual ICollection<VehiclesFuels> VehiclesFuels { get; set; } = new List<VehiclesFuels>();
    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}