// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using FUEL_DISPATCH_API.DataAccess.Models;

namespace FUEL_DISPATCH_API.DataAccess.Models
{
    public partial class FUEL_DISPATCH_DBContext
    {

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
