// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FUEL_DISPATCH_API.DataAccess.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace FUEL_DISPATCH_API.DataAccess.Models
{
    public partial class FUEL_DISPATCH_DBContext
    {
        private IFUEL_DISPATCH_DBContextProcedures _procedures;

        public virtual IFUEL_DISPATCH_DBContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new FUEL_DISPATCH_DBContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IFUEL_DISPATCH_DBContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class FUEL_DISPATCH_DBContextProcedures : IFUEL_DISPATCH_DBContextProcedures
    {
        private readonly FUEL_DISPATCH_DBContext _context;

        public FUEL_DISPATCH_DBContextProcedures(FUEL_DISPATCH_DBContext context)
        {
            _context = context;
        }
    }
}
