// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class FuelTypes
{
    public int Id { get; set; }

    public string Type { get; set; }

    public virtual ICollection<Vehicles> VehicleToken { get; set; } = new List<Vehicles>();
}