// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FUEL_DISPATCH_API.DataAccess.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace FUEL_DISPATCH_API.DataAccess.Models
{
    public partial interface IFUEL_DISPATCH_DBContextProcedures
    {
    }
}
