// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Make
{
    public int Id { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string? Makename { get; set; }
    [JsonIgnore]
    public virtual ICollection<Vehicle> VehicleGeneration { get; set; } = new List<Vehicle>();
    [JsonIgnore]
    public virtual ICollection<Vehicle> VehicleMake { get; set; } = new List<Vehicle>();
}