// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Makes
{
    public int Id { get; set; }

    public string Make { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Vehicles> VehiclesGeneration { get; set; } = new List<Vehicles>();

    public virtual ICollection<Vehicles> VehiclesMake { get; set; } = new List<Vehicles>();
}