// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class MethodOfProvidingFuel
{
    public int Id { get; set; }

    public string? MethodName { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Drivers_MethodsOfProvideFuel> Drivers_MethodsOfProvideFuel { get; set; } = new List<Drivers_MethodsOfProvideFuel>();
}