// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class ModEngine
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? ImgUrl { get; set; }

    public string? Url { get; set; }

    public int? GenerationId { get; set; }

    [JsonIgnore] public virtual Generation? Generation { get; set; }
    [JsonIgnore] public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}