// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.Text.Json.Serialization;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Model
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? ImgUrl { get; set; }

    public string? Url { get; set; }

    public int? MakeId { get; set; }

    [JsonIgnore] public virtual ICollection<Generation> Generations { get; set; } = [];

    [JsonIgnore] public virtual Make? Make { get; set; }
    [JsonIgnore] public virtual ICollection<Vehicle> Vehicles { get; set; } = [];
}