// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class OdometerMeasure
{
    public int Id { get; set; }

    public string? Measurename { get; set; }

    public virtual ICollection<Vehicle> Vehicle { get; set; } = new List<Vehicle>();
}