// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Road
{
    public int Id { get; set; }

    public string? APoint { get; set; }

    public string? BPoint { get; set; }

    public TimeOnly? StimatedTime { get; set; }

    public string? Status { get; set; }

    public int? ZoneId { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<WareHouseMovement> WareHouseMovements { get; set; } = new List<WareHouseMovement>();

    public virtual Zone? Zone { get; set; }
}