// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Roads
{
    public int Id { get; set; }

    public string Apoint { get; set; }

    public string Bpoint { get; set; }

    public TimeOnly? StimatedTime { get; set; }

    public string Status { get; set; }

    public int? ZoneId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Dispatch> Dispatch { get; set; } = new List<Dispatch>();

    public virtual Zones Zone { get; set; }
}