// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Role
{
    public int Id { get; set; }

    public string RolName { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<UsersRols> UsersRols { get; set; } = new List<UsersRols>();
    public virtual ICollection<Users> Users{ get; set; } = new List<Users>();
}