// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class UsersTokens
{
    public int Id { get; set; }

    public string Token { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? ExpData { get; set; }

    public int? UserId { get; set; }
}