// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class UsersRols
{
    public int UserId { get; set; }

    public int RolId { get; set; }

    public virtual Role Rol { get; set; }

    public virtual Users User { get; set; }
}