// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.Text.Json.Serialization;
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class User
{
    public int Id { get; set; }

    public string? Email { get; set; }

    public string FullName { get; set; } = null!;

    public string Username { get; set; } = null!;

    public string Password { get; set; } = null!;

    public string PhoneNumber { get; set; } = null!;

    public DateTime BirthDate { get; set; }

    public string FullDirection { get; set; } = null!;

    public string? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }
    public int? DriverId { get; set; }
    [JsonIgnore]
    public virtual Driver? Driver { get; set; }
    [JsonIgnore]
    public virtual ICollection<UsersRols> UsersRols { get; set; } = new List<UsersRols>();
    [JsonIgnore]
    public virtual ICollection<Role>? Rols { get; set; }
    [JsonIgnore]
    public virtual ICollection<UsersCompanies> UsersCompanies { get; set; } = new List<UsersCompanies>();   
    public virtual ICollection<Companies> Companies { get; set; } = new List<Companies>();
}
    