// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Users
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string FullName { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string PhoneNumber { get; set; }

    public DateTime BirthDate { get; set; }

    public string FullDirection { get; set; }

    public int? DriverId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Drivers Driver { get; set; }

    public virtual ICollection<UsersRols> UsersRols { get; set; } = new List<UsersRols>();

    public virtual ICollection<BranchOffices> BranchOffice { get; set; } = new List<BranchOffices>();
}