// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Vehicles
{
    public string Token { get; set; }

    public int? MakeId { get; set; }

    public int? ModelId { get; set; }

    public int? GenerationId { get; set; }

    public int? ModEngineId { get; set; }

    public int? DriverId { get; set; }

    public string Status { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public decimal? AverageConsumption { get; set; }

    public string Color { get; set; }

    public virtual ICollection<Dispatch> Dispatch { get; set; } = new List<Dispatch>();

    public virtual Drivers Driver { get; set; }

    public virtual Makes Generation { get; set; }

    public virtual Makes Make { get; set; }

    public virtual ModEngine ModEngine { get; set; }

    public virtual Models Model { get; set; }

    public virtual ICollection<FuelTypes> Fuel { get; set; } = new List<FuelTypes>();
}