// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.Text.Json.Serialization;
using System;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Vehicle
{
    public string? Token { get; set; }

    public int? MakeId { get; set; }

    public int? ModelId { get; set; }

    public int? GenerationId { get; set; }

    public int? ModEngineId { get; set; }

    public int? DriverId { get; set; }

    public string? Status { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public decimal? AverageConsumption { get; set; }

    public string? Color { get; set; }

    public decimal? Capacity { get; set; }

    public int? MeasureId { get; set; }

    public int Id { get; set; }

    public string? Plate { get; set; }
    [JsonIgnore]
    public virtual ICollection<Dispatch> Dispatch { get; set; } = new List<Dispatch>();
    [JsonIgnore]
    public virtual ICollection<Driver> Driver { get; set; } = new List<Driver>();
    [JsonIgnore]
    public virtual Driver? DriverNavigation { get; set; }
    [JsonIgnore]
    public virtual Make? Generation { get; set; }
    [JsonIgnore]
    public virtual Make? Make { get; set; }
    [JsonIgnore]
    public virtual Measure? Measure { get; set; }
    [JsonIgnore]
    public virtual ModEngine? ModEngine { get; set; }
    [JsonIgnore]
    public virtual Model? Model { get; set; }
    [JsonIgnore]
    public virtual ICollection<VehiclesFuels> VehiclesFuels { get; set; } = new List<VehiclesFuels>();
    [JsonIgnore]
    public virtual ICollection<FuelType> Fuels { get; set; } = new List<FuelType>();
}