// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.Text.Json.Serialization;
using System;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Vehicle
{
    public string? Ficha { get; set; }

    public int? MakeId { get; set; }

    public int? ModelId { get; set; }

    public int? GenerationId { get; set; }

    public int? ModEngineId { get; set; }

    public int? DriverId { get; set; }

    public string? Status { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public decimal? AverageConsumption { get; set; }

    public string? Color { get; set; }

    public decimal? FuelTankCapacity { get; set; }

    public int? OdometerMeasureId { get; set; }

    public int Id { get; set; }

    public string? Plate { get; set; }

    [JsonIgnore] public virtual ICollection<WareHouseMovement> WareHouseMovements { get; set; } = new List<WareHouseMovement>();

    [JsonIgnore] public virtual Driver? Driver { get; set; }

    [JsonIgnore] public virtual Generation? Generation { get; set; }

    [JsonIgnore] public virtual Make? Make { get; set; }

    [JsonIgnore] public virtual OdometerMeasure? Measure { get; set; }

    [JsonIgnore] public virtual ModEngine? ModEngine { get; set; }

    [JsonIgnore] public virtual Model? Model { get; set; }


    [JsonIgnore] public virtual ICollection<WareHouseMovementRequest> Requests { get; set; } = new List<WareHouseMovementRequest>();

    [JsonIgnore] public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}