// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class VehiclesFuels
{
    public int FuelId { get; set; }

    public int VehicleId { get; set; }

    public virtual FuelType Fuel { get; set; } = null!;

    public virtual Vehicle Vehicle { get; set; } = null!;
}