// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace FUEL_DISPATCH_API.DataAccess.Models;

public partial class Zone
{
    public int Id { get; set; }

    [Required] public string? FullZoneSpecs { get; set; }
    [Required] public string? Code { get; set; }
    [Required] public int CompanyId { get; set; }
    public string? Status { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }
    [JsonIgnore] public virtual Companies? Company { get; set; }
    [JsonIgnore] public virtual ICollection<Road> Road { get; set; } = new List<Road>();
}